CalcPressure
atomec-project/atoMEC pull request #55
Opened 2021-08-03 11:55 UTC by ekaterinats

Added function to calculate electronic pressure

2021-08-03 12:33 UTC, timcallow requested changes

2021-08-03 12:33 UTC, timcallow commented on atoMEC/models.py
> +        nmax,
I suggest using a default value here, `nmax=config.nmax` since this was set earlier in `CalcEnergy`.

2021-08-03 12:33 UTC, timcallow commented on atoMEC/models.py
> +        lmax,
same as above

2021-08-03 12:33 UTC, timcallow commented on atoMEC/models.py
> +        """
Add a print statement to say that pressure is being calculated

2021-08-03 12:33 UTC, timcallow commented on atoMEC/models.py
> +
Add a conversion factor to convert from Ha to GPa. I suggest to add this variable in the `unitconv` module and then import it.

Then add print statement for the pressure and print it in both sets of units (Ha and GPa). See for example how the temperature is printed in the `Atom` class.

2021-08-05 09:25 UTC, ekaterinats commented
see my latest changes @timcallow

2021-08-05 09:57 UTC, timcallow requested changes

2021-08-05 09:57 UTC, timcallow commented on atoMEC/models.py
> +        print(
Could you add some formatting to this print statement? You can find some examples of how this is done in `writeoutput.py`, also here: https://www.programiz.com/python-programming/methods/string/format.

I would suggest around 5/6 significant figures, you can try with both exponential (e/E) or general (g/G) formatting and see what looks best.

2021-08-05 09:57 UTC, timcallow commented on atoMEC/unitconv.py
> +ha_to_gpa = 1e-9 * 4.3597e-18 / ((5.2918e-11) ** 3)
This would be best written as just a single number, whatever the above is equal to

2021-08-05 10:26 UTC, ekaterinats commented
check my new changes @timcallow

2021-08-05 13:22 UTC, timcallow commented
@ekaterinats hmm getting an error as follows

![Screenshot from 2021-08-05 15-20-16](https://user-images.githubusercontent.com/18050753/128356985-59bed6f5-d51d-4141-9cd9-2b4aff841aec.png)

![Screenshot from 2021-08-05 15-21-33](https://user-images.githubusercontent.com/18050753/128356979-e260f2c8-5aea-45c7-89cb-e1b5ca49f662.png)

2021-08-05 14:14 UTC, timcallow reviewed
LGTM (see separate comment regarding default `nmax` and `lmax` parameters)

2021-08-05 14:42 UTC, timcallow commented
@ekaterinats I'm still not sure why it wasn't working but I think I found a way round for now. Can you check it is working for you now without having to input `nmax` and `lmax` parameters into `CalcPressure`?

2021-08-09 17:10 UTC, merged